package models;

import java.util.Date;

public class User {
    // initialize variables corresponding to the fields in the user_data table in DB
    // make them private, so they can't be accessed outside the class without getters and setters
    private Integer userId; // Must be unique primary key, generated by postgres/DB at time of record creation
    private String firstName; // Must not be null. First Letter must be capitalized
    private String lastName; // Must not be null. First letter must be capitalized
    private String email; // Can be null. can contain alpha-numeric, hyphens, underscore, dash or dash. MUST contain the @ symbol, and end with a period followed by 3 letters. limit 20 characters
    private Integer phNum; // user's phone number trimmed to exclude any non-numeric characters. must be 10 digits in length
    private String ssn; // Must be a sequence of chars matching the pattern 'XXX-XX-XXXX', must be unique and not null

    private Date dob;   // will be handled as int'YYYY', int 'MM',' int 'DD' at the controller(Java) layer.
                        // Handled as a String at the DB layer in the format 'YYYY-MM-DD'
                        // Handled as a String "MM/DD/YYYY" at the presentation layer(Java Console)


    private String userName; // case-sensitive, unique, not null, 8-12 alpha-numeric characters. can include underscores or all symbols from shift+ 0-9. no apostrophes, equals, or forward slash
                                // cannot contain the user's first or last name, 'user' or 'username', or have characters that repeat 4 or more times
                                // cannot be null

    private String password; //case-sensitive, unique, not null, 8-12 alpha-numeric characters. can include underscores or all symbols from shift+ 0-9. no apostrophes, equals, or forward slash
                            // must be unique, not contain 'pass' or 'password', have at least one number or special symbol
                            // must not contain any characters that repeat 4 or more times

    private Integer fico; // credit score. integer must be 3 digits in length


    // Create constructors for various use-cases of the Customer class
    // Should be public and non-static as they will be used outside the class

    // default no args constructor
    public User(){

    }

    // for Loan Officer queries
    public User (Integer userId, String firstName, String lastName, Integer fico){
        this.userId = userId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.fico = fico;
    }

    // constructor used for login/logout
    public User (String firstName, String lastName, String password, Integer userId){
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.userId = userId;
    }

    // constructor for new account creation, or superUser query/modification
    public User (Integer userId, String firstName, String lastName, String email, Integer phNum, String ssn, Date dob, String userName, String password, Integer fico){
        this.userId = userId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phNum = phNum;
        this.ssn = ssn;
        this.dob = dob;
        this.userName = userName;
        this.password = password;
        this.fico = fico;
    }

    // create getter and setter methods for passing information to/from the console
    // these methods should be public and non-static, so they can be called by other classes
    // getters are expected to return data, so should have a return type matching the instance variable type
    // setters do not return anything, so should have a void return type

    // customer ID
    public Integer getuserId() {
        return this.userId;
    }
    public void setUserId(Integer userId){
        this.userId = userId;
    }

    // first name
    public String getFirstName() {
        return this.firstName;
    }
    public void setFirstName(String firstName){
        this.firstName = firstName;
    }

    // last name
    public String getLastName() {
        return this.lastName;
    }
    public void setLastName(String lastName){
        this.lastName = lastName;
    }

    //email String
    public String getEmail(){
        return this.email;
    }
    public void setEmail(String email){
        this.email = email;
    }

    //phNum Integer
    public Integer getPhNum(){
        return this.phNum;
    }
    public void setPhNum(Integer phNum){
        this.phNum = phNum;
    }

    // SSN
    public String getSsn() {
        return this.ssn;
    }
    public void setSsn(String ssn){
        this.ssn = ssn;
    }

    // DOB
    public Date getDob(){
        return this.dob;
    }
    public void setDob(Date dob){
        this.dob = dob;
    }

    // Username
    public String getUserName() {
        return this.userName;
    }
    public void setUserName(String userName){
        this.userName = userName;
    }

    // Password
    public String getPassword() {
        return this.password;
    }
    public void setPassword(String password){
        this.password = password;
    }

    // FICO Score
    public Integer getFico() {
        return this.fico;
    }
    public void setFico(Integer fico){
        this.fico = fico;
    }

    // override toString() method for this class
    @Override
    public String toString(){
        return firstName + " " + lastName + "\n" +
                "Password: " + password + "\n" + "userid" + userId;
    }

}
